name: Deploy Javadoc to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.5-openjdk-17

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Javadoc
        run: mvn javadoc:javadoc -Dlocale=de_DE -DadditionalJOption=-Xdoclint:none

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Prepare Javadoc output
        run: |
          mkdir -p public
          cp -r target/reports/apidocs/* public/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
